name: Chromatic Main and Active PRs only
on:
    push:
        branches:
            - main
    pull_request:
        types: [assigned, ready_for_review, review_requested]

jobs:
    chromatic:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Use Node.js 20.x
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
            - name: install
              run: yarn
            - name: create partials
              run: yarn partialsToJs
            - uses: chromaui/action@v11.3.0
              with:
                  # 👇 Chromatic projectToken, refer to the manage page to obtain it.
                  projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
                  exitOnceUploaded: true
                  onlyChanged: false
                  traceChanged: false
                  diagnostics: true
                  skip: ${{ github.event.pull_request.draft == true }}
            - uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: chromatic-build-artifacts-${{ github.run_id }}
                  path: |
                      chromatic-diagnostics.json
                      **/build-storybook.log
